import Header from "@/components/header-nav";
import { getSession } from "@/lib/auth";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getSession();
  return (
    <html lang="en">
      <body>
      <Header session={session} />
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
